// src/utils/nakshatraUtils.js
export const nakshatraNameToId = {
  "Ashwini": 1,
  "Bharani": 2,
  "Krittika": 3,
  "Rohini": 4,
  "Mrigashira": 5,
  "Ardra": 6,
  "Punarvasu": 7,
  "Pushya": 8,
  "Ashlesha": 9,
  "Magha": 10,
  "Purva Phalguni": 11,
  "Uttara Phalguni": 12,
  "Hasta": 13,
  "Chitra": 14,
  "Swati": 15,
  "Vishakha": 16,
  "Anuradha": 17,
  "Jyeshtha": 18,
  "Mula": 19,
  "Purva Ashadha": 20,
  "Uttara Ashadha": 21,
  "Shravana": 22,
  "Dhanishta": 23,
  "Shatabhisha": 24,
  "Purva Bhadrapada": 25,
  "Uttara Bhadrapada": 26,
  "Revati": 27,
  
  // Tamil names (add these if you also use Tamil names in your DB)
  "அசுவினி": 1,
  "பரணி": 2,
  "கிருத்திகை": 3,
  "ரோகிணி": 4,
  "மிருகசிரிஷம்": 5,
  "திருவாதிரை": 6,
  "புனர்பூசம்": 7,
  "பூசம்": 8,
  "ஆயில்யம்": 9,
  "மகம்": 10,
  "பூரம்": 11,
  "உத்திரம்": 12,
  "அஸ்தம்": 13,
  "சித்திரை": 14,
  "சுவாதி": 15,
  "விசாகம்": 16,
  "அனுஷம்": 17,
  "கேட்டை": 18,
  "மூலம்": 19,
  "பூராடம்": 20,
  "உத்திராடம்": 21,
  "திருவோணம்": 22,
  "அவிட்டம்": 23,
  "சதயம்": 24,
  "பூரட்டாதி": 25,
  "உத்திரட்டாதி": 26,
  "ரேவதி": 27
};

export const nakshatraIdToName = Object.fromEntries(
  Object.entries(nakshatraNameToId).map(([name, id]) => [id, name])
);